version: '3'

services:

  nats-server:
    image: nats:latest

  client-gateway:
    build: 
      context: ./client-gateway
      dockerfile: dockerfile.prod
    ports:
      - ${PORT_CLIENT_GATEWAY}:3000
    environment:
      - PORT=3000
      - NATS_SERVER=nats://nats-server:4222
      - SECRET_JWT=${SECRET_JWT}
    image: southamerica-east1-docker.pkg.dev/microservicios-shop/image-registry/client-gateway-prod

  products-ms:
    build: 
      context: ./products-ms
      dockerfile: dockerfile.prod
    environment:
      - PORT=3001
      - NATS_SERVER=nats://nats-server:4222
      - DATABASE_URL=file:./dev.db
    image: southamerica-east1-docker.pkg.dev/microservicios-shop/image-registry/products-ms-prod

  # order-db:
  #   container_name: order-db
  #   image: postgres:16.2
  #   restart: always
  #   volumes:
  #     - ./order-ms/postgres:/var/lib/postgresql/data
  #   ports:
  #     - 5433:5432
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: 123456
  #     POSTGRES_DB: orders

  order-ms:
    build: 
      context: ./order-ms
      dockerfile: dockerfile.prod
      args:
        - POSTGRES_DB=${POSTGRES_DB}
    environment:
      - PORT=3002
      - NATS_SERVER=nats://nats-server:4222
      - DATABASE_URL=${POSTGRES_DB}
    image: southamerica-east1-docker.pkg.dev/microservicios-shop/image-registry/orders-ms-prod

  auth-ms:
    build: 
      context: ./auth-ms
      dockerfile: dockerfile.prod
    image: southamerica-east1-docker.pkg.dev/microservicios-shop/image-registry/auth-ms-prod
    environment:
      - PORT=3004
      - NATS_SERVER=nats://nats-server:4222
      - MONGO_DB=${MONGO_DB}
      - SECRET_JWT=${SECRET_JWT}

  payments-ms:
    build: 
      context: ./payments-ms
      dockerfile: dockerfile.prod
    ports:
      - 3003:3003
    environment:
      - PORT=3003
      - SECRET_KEY_STRIPE=${SECRET_KEY_STRIPE_PAYMENTS}
      - SECRET_KEY_WEBHOOK_STRIPE=${SECRET_KEY_WEBHOOK_STRIPE_PAYMENTS}
      - SUCCES_URL=http://localhost:3003/payment/success
      - CANCEL_URL=http://localhost:3003/payment/cancel
      - NATS_SERVER=nats://nats-server:4222
    image: southamerica-east1-docker.pkg.dev/microservicios-shop/image-registry/payments-ms-prod