apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: orders-ms-prod
  name: orders-ms-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders-ms-prod
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: orders-ms-prod
    spec:
      containers:
        - image: southamerica-east1-docker.pkg.dev/microservicios-shop/image-registry/orders-ms-prod
          name: orders-ms-prod
          env:
            - name: NATS_SERVER
              value: nats://nats
            - name: PORT
              value: "3002"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: orders-secrets
                  key: database_url
          resources: {}
status: {}
