apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: products-ms-prod
  name: products-ms-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: products-ms-prod
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: products-ms-prod
    spec:
      containers:
        - image: southamerica-east1-docker.pkg.dev/microservicios-shop/image-registry/products-ms-prod
          name: products-ms-prod
          env:
            - name: PORT
              value: "3001"
            - name: NATS_SERVER
              value: nats://nats
            - name: DATABASE_URL
              value: file:./dev.db
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
status: {}
